[book]
authors = ["Jason"]
language = "zh-cn"
multilingual = false
src = "src"
title = "化工知识库-hao.aihg.top"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["assets/fzf.umd.js", "assets/elasticlunr.js", "assets/mermaid.min.js", "assets/mermaid-init.js"]
site-url = "https://hao.aihg.top/chemistry-basic/"

[preprocessor.katex]
after = ["links"]
